## Project info
site_name: Cat Elevator
site_description: My personal digital garden
site_author: Los7key
site_url: https://www.catelevator.com
site_description: >-
  SOMETHING SHOULD GO HERE

## Copyright
copyright: Copyright &copy; 2020 - 2023 

## Configurations start here
plugins:
  - search
  # - awesome-pages
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  #- mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - footnotes
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  ##- pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  font:
    text: Castoro
  favicon: assets/images/catelev.png
  logo: assets/images/catelev.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - header.autohide  

  palette:
  #   # Auto mode
  # - media: "(prefers-color-scheme)"
  #   toggle:
  #     icon: material/brightness-auto
  #     name: Switch to light mode

  #   # Light mode
   - media: '(prefers-color-scheme: light)'
     scheme: garden
     #scheme: default
     primary: grey
     accent: grey
     toggle:
       icon: material/toggle-switch-off-outline
       name: Switch to dark mode

  #   # Dark mode
   - media: '(prefers-color-scheme: dark)'
     scheme: garden_dark
     toggle:
       icon: material/toggle-switch
       name: Switch to light mode

extra_css:
  - stylesheets/garden.css
  - stylesheets/links.css
#- stylesheets/extra.css

#extra_javascript:
  #- javascripts/extra.js

#extra:
#  analytics:
#    provider: google
#    property: G-S6XNBQV005

#  social:
    # - icon: fontawesome/brands/github-alt
    #  link: https://github.com/jellyfishsizzle
        # repo_name: jellyfishsizzle/garden
        # repo_url: https://github.com/jellyfishsizzle/garden
