---
site_name: Jellyfish Sizzle
site_description: My personal digital garden
site_author: Jellyfishsizzle
site_url: https://garden.jellyfishsizzle.xyz
nav:
  - Introduction: index.md
  - Cannabis:
      - Strain Catalogue:
          - strains/README.md
          - Black Jack: strains/black-jack.md
          - Blueberry Muffin: strains/blueberry-muffin.md
          - Chocolate Tonic CBD: strains/chocolate-tonic-cbd.md
          - Knight's Templar: strains/knights-templar-og.md
          - Napali Pink: strains/napali-pink.md
          - Skywalker OG: strains/skywalker-og.md
          - Vanilla Frosting: strains/vanilla-frosting.md
          - Venom OG: strains/venom-og.md
      - Growing Tips:    
          - outside.md
  - Code:
      - tech/code/README.md
      - Perl: tech/code/perl.md
      - Emojis: emojis.md
  - Humor:
      - Dad Jokes: dad-jokes.md
      - Nerd Jokes: nerd-jokes.md
  - Music:
      - Pink Floyd: music/pink-floyd.md
  - Security:
      - tech/security/README.md
      - Binary exploitation: tech/security/binary-exploitation.md
      - TTY and rev shells: tech/security/fix-tty-for-rev-shells.md
      - OSINT: tech/security/osint-tips.md
      - Pivoting w/chisel: tech/security/pivoting-with-chisel.md
      - SQL Injection: tech/security/sql-injection-cheatsheet.md
      - SSH and tunneling: tech/security/ssh-and-tunneling.md
  - UNIX:
      - tech/unix/README.md
      - BASH Prompts: tech/unix/bash-prompts.md
      - HTTP Cheatsheet: tech/unix/handy-http-commands.md
      - XFCE Themes: tech/unix/xfce-theme-installation.md
  - Web:
      - tech/web/README.md
      - This site: tech/web/how-my-site-works.md
      - History of InfoSec and WWW: tech/web/history-of-infosec-and-www.md

plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  favicon: assets/images/favicon.ico
    #logo: img/logo.bmp
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: grey
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
  - stylesheets/links.css
  - stylesheets/jf.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jellyfishsizzle
        #- icon: fontawesome/solid/rss
        #link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index

repo_name: jellyfishsizzle/garden
repo_url: https://github.com/jellyfishsizzle/garden
